### ISSUE TITLE
Aktualnosci slider - prosba o review

### ISSUE THREAD

**Issue by marcinbelczewski** [IHS-Gdansk/website#15]
Nakopypastowalem co sie dalo i wyszedl mi jakis slajder do aktualnosci - nie wiem czy chcemy to w ten sposob robic ale podrzucam jakby co pod rozwage.

**Comment by marcinbelczewski** [comment]
Zapomnialem napisac ze to jest na branczu "aktualnosci_slider"

**Comment by SebastianCelejewski** [comment]
Dla mnie super.

**Comment by SebastianCelejewski** [comment]
W przypadku większej liczby ciekawostek proponuję w sliderze umieścić kilka ostatnich (3..5), a poniżej link typu ,,Archiwum wydarzeń'', czy coś w tym stylu.

**Comment by IHS-Gdansk** [comment]
Jednak zrobiłem to trochę inaczej niedawno więc to zamykam
