### ISSUE TITLE
Przymiotniki/przysłówki

### ISSUE THREAD

**Issue by wedkarz** [IHS-Gdansk/website#21]
Przymiotniki/przysłówki brzmią pretensjonalnie: "wiele monitorów", "szybkie procesory", "dużo RAM". Możemy dodać konkrety?

**Comment by agatajachimowicz** [comment]
Mam to samo wrażenie. To opis dla kogoś nie z IT.

**Comment by wedkarz** [comment]
Jakiś komentarz do zamknięcia?

**Comment by IHS-Gdansk** [comment]
pół roku bez pull requesta to raczej oznacza że nikomu jednak nie przeszkadza ;-)
