### ISSUE TITLE
Dev ikonki 

### ISSUE THREAD

**Issue by theimowski** [IHS-Gdansk/website#29]
Może fajne technologiczne ikonki dodałyby +5 punktów do sekcji "narzędzia" ?
Np:
http://vorillaz.github.io/devicons
albo
http://fizzed.com/oss/font-mfizz

Przykład oferty pracy "wzbogaconej" o ikonki, wydaje mi się że to nakręca geeków:
https://buffer.com/journey/back-end-developer

**Comment by theimowski** [comment]
sneak peek

![image](https://cloud.githubusercontent.com/assets/5909015/10715353/513c5ad8-7b14-11e5-9c17-39caa4f96f51.png)

**Comment by marcinbelczewski** [comment]
ja jestem bardzo za - dawaj pull requesta

**Comment by theimowski** [comment]
Ikonki można dodać albo standardowo, dołączając wszystkie cssy i fonty do repo, albo dużo łatwiej za pomocą CDN. 
Ta druga opcja wymaga jednak podczas testowania odpalonego serwera http - np. Ja sobie odpaliłem w nodzie.
Spowodowane to jest tym, ze cdn nie ogarnie po protokole file://
Którą opcję wolimy?

**Comment by IHS-Gdansk** [comment]
Ja nie mam nic przeciwko hostowaniu lokalnemu zeby testowac - zawsze moge odpalic sam plik w przegladarce jak mi nie zalezy na ogladaniu ikon akurat. Jedyne co to fajnie by bylo byc w miare spojnym czyli albo ikony do wiekszosci albo nie - a nie wiem czy idzie zdobyc ikony do wszystkiego

**Comment by dawgeb** [comment]
Pamiętajcie że mamy tak azura skonfigurowanego że zmergowane zmiany do mastera od razu trafiają tutaj: http://ihsgdansk-stage1.azurewebsites.net
a dopiero ja muszę "sloty" podmienić żeby się pojawiły na naszej stronie głównej

**Comment by IHS-Gdansk** [comment]
A to nie było tak że jak wpuszam do mastera to mam na http://ihsgdansk-stage1.azurewebsites.net a jak wpuszam na branch "Prod" to idzie na ihsgdansk.com? Bo dokładnie przy ostatnich kilku puszach tak mi to wyglądało że działa - ostatnio wczoraj ;-)

**Comment by dawgeb** [comment]
tak, oczywiscie masz racje! zapomnielem o tym branch-u "Prod"

**Comment by SebastianCelejewski** [comment]
Done. Already in Prod.
