### ISSUE TITLE
Aktualności karuzela - take 2

### ISSUE THREAD

**Issue by marcinbelczewski** [IHS-Gdansk/website#30]
Hej. Rzućcie proszę okiem jeśli możecie na implementację aktualnosci w formie karuzeli plus nowa relacja Lambda Days 2016. 
Nie wiem czy czegos ostro nie spieprzylem bo karuzela na ciekawostkach z której "małpowałem" byla zrobiona jakby przez dwie osoby - w dwoch miejscach byl JavaScript inicjujacy karuzele, w dwoch miejscach stylowanie itp. Poczysciłem jak umiałem i dodałem aktualności plus nową relację z konferencji. Jak prawdziwy kozak wpuszowałem do brancha "master" czyli widoczne jest tutaj: http://ihsgdansk-stage1.azurewebsites.net/ ale nie na oficjalnym websajcie. @theimowski @tomgi @SebastianCelejewski @onliner10

**Comment by theimowski** [comment]
U siebie na mobilu nie mogę otworzyć szczegółów żadnej aktualności z karuzeli (brak interakcji) - ale to Windows Phone, nie wiem jak normalne mobilki ;)

**Comment by marcinbelczewski** [comment]
Winne były sassowe ustawienia rozmiarów zależne od rozdzielczości. Takie ustawienia też są dla "ciekawostek" i jakoś działa a dla aktualności nie chce. Nie rozumiem tego do końca więc usunąłem i jest lepiej ;-) Nadal są dziwactwa w stylu dziwnie przeskalowanych obrazków ale na to chyba już tylko Agata coś poradzi ;-)

**Comment by theimowski** [comment]
teraz wygląda spoko. Przy okazji nasunął mi się zupełnie inny pomysł (pewnie nice-to-have na kiedyś tam w przyszłości) - możnaby ograniczyć ilość contentu dla mobila (zmniejszyć ilość osób z sekcji "Ludzie" itd), bo obecnie jest sporo do scrollowania

**Comment by marcinbelczewski** [comment]
Dobry pomysł! Mozna zostawić tylko moje zdjęcie ;)

**Comment by SebastianCelejewski** [comment]
Pierwsze zdjęcie ma kolory, jakby przeleżało w szafie jakieś 100 lat. To jest celowy zabieg artystyczny?

**Comment by marcinbelczewski** [comment]
Chyba filtr jakiś. Agata zna szczegóły w każdym razie zabieg raczej celowy
