### ISSUE TITLE
Aktualności: Messer - Property Based Testing with F#

### ISSUE THREAD

**Issue by theimowski** [IHS-Gdansk/website#8]
Mógłbym dodać krótki opis ostatniej akademii messera, tylko zastanawiam się czy zrobić to w nowej, 4. kolumnie? Macie już pomysł jak nowe wpisy do aktualności będziecie chcieli dodawać?

**Comment by IHS-Gdansk** [comment]
a może zbierzemy jeszcze z 1-2 dodatkowe i zrobimy wtedy, może pod koniec następnego tygodnia, drugi rząd? np. Siekiera jedzie na fajną konferencje do Barcelony, poproszę go żeby pare fotek pstryknął i coś napisał... jeszcze z jeden temat byśmy potrzebowali...

**Comment by marcinbelczewski** [comment]
To bedzie takie samo cos jak ciekawostki.

**Comment by marcinbelczewski** [comment]
Agata mi napisała żebyś używał grida z bootstrapa i bedzie dobrze ;)

**Comment by theimowski** [comment]
ok, potrzebowałbym tylko jeszcze jakiejś fotki / fotek z wydarzenia @SebastianCelejewski

**Comment by SebastianCelejewski** [comment]
@theimowski Wysłałem na Twój adres firmowy cztery zdjęcia.

**Comment by marcinbelczewski** [comment]
a apropos 1-2 dodatkowych to moze cos "zwienimy" z ajejczes magazin?

2015-10-16 22:10 GMT+02:00 Sebastian Celejewski notifications@github.com:

**Comment by SebastianCelejewski** [comment]
Wszystkie zdjęcia mojego autorstwa, które kiedykolwiek pojawiły się w Ajejczes Magazin, są też u mnie w udostępnionym katalogu. Pozostałe zaraz udostępnię na Google Drive.

**Comment by IHS-Gdansk** [comment]
Super dzieki!
